---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: nginxhello
  namespace: default
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: gitops-lab-deploy-auth
  url: ssh://github.com/salimkashif/gitops-lab-deploy

