---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginxhello
  name: nginxhello
spec:
  ports:
  - port: 80
    name: http
    protocol: TCP
    targetPort: http
  selector:
    app: nginxhello
